### ISSUE TITLE
Permalinks to start times

### ISSUE THREAD

**Issue by hastebrot** [sgt-kabukiman/horaro#1]
Being able to reference certain runs per hyperlink (URL fragment) would be nice. E.g. https://horaro.org/agdq/2016#start_t-1451838600

**Edit:** Maybe the date/time or unix timestamp is insufficient to have permalinks (since the schedule can be edited). Instead maybe a run id or a hash could be used.

BTW: Amazing work :+1:

**Comment by sgt-kabukiman** [comment]
It doesn't help with time ranges, but you can already do stuff like [#mario](https://horaro.org/agdq/2016#mario) or [?highlight=mario](https://horaro.org/agdq/2016?highlight=mario) (separate multiple terms with comma, like ``#mario,metroid``).

**Comment by hastebrot** [comment]
Wow, very nice.

**Comment by sgt-kabukiman** [comment]
Just to estimate the urgency, are your usecases handled by this already?

**Comment by hastebrot** [comment]
Yes. Using search terms, as you suggested, seems to be even better. It is even possible to refer runs with spaces in the run name using `%20` for space, e.g. [agdq/2016?highlight=super%20mario%20kart](https://horaro.org/agdq/2016?highlight=super%20mario%20kart). So my use-case is handled by this, thanks.

Can be closed, if you like.

**Comment by sgt-kabukiman** [comment]
Perfect. Also, thanks for the compliments. :-)

**Comment by hastebrot** [comment]
Yes, this shows again, the speedrun community is capable to create really great software!
