### ISSUE TITLE
Trying to setup a Horaro instance

### ISSUE THREAD

**Issue by moutonnoireu** [sgt-kabukiman/horaro#5]
Is there a special rewrite to use with nginx ? All links are formed like that http://domain/-/register (note the ``-``), in case of the register link. It create a 404. :(

**Comment by sgt-kabukiman** [comment]
How is your webserver configured right now? Do you have a "catch all" rewrite rule like in https://github.com/sgt-kabukiman/horaro/blob/master/resources/nginx.conf#L21-L30 configured?

**Comment by moutonnoireu** [comment]
Just tested with your recommendation and nginx thow me this error : 
``[error] 3592#3592: *1 rewrite or internal redirection cycle while redirect to named location "@index", client: XX.XX.XX.XX, server: host.domain, request: "GET /-/register HTTP/2.0", host: "host.domain", referrer: "https://host.domain/"``

**Comment by moutonnoireu** [comment]
Ok, i fixed the error myslef, was a nginx issue ! Sorry for the trouble ;)

**Comment by sgt-kabukiman** [comment]
No worries :-)
