### ISSUE TITLE
CSV import example file not working

### ISSUE THREAD

**Issue by patrickgh3** [sgt-kabukiman/horaro#8]
First off, thanks a bunch for making and maintaining Horaro! It's been very convenient for my community's niche Twitch marathons. :)

I was helping someone try and import our schedule spreadsheet as a CSV. Despite getting it in the correct format (I think), I kept getting the error message "Could not recognize the file format.
JSON or CSV; maximum allowed file size is 4096 KiB." Then I tried copying the "A good CSV file looks something like this:" example into a file and uploading it, and it gave me the same error. I believe the error might be in the actual importer, but it's possible that the example text on the page is just not correct, I'm not sure which.

I also tried downloading our previous year's schedule as a JSON file and uploading that (just to test), and it also gave me the same error.

**Comment by sgt-kabukiman** [comment]
When wrapping Horaro in an Alpine-based Docker container, I broke Symfony's MIME type detection because the `file`  utility is not installed by default. The missing package is installed now and as far as I could test, uploading files should work again.

Sorry for the brainfart on my end.
